use_frameworks!

platform :ios, '8.0'

target 'MYNetWorking_Example' do
  pod 'MYNetWorking', :path => '../'

  target 'MYNetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
